name: Delete Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: The tag to delete

jobs:
  delete-tag:
    runs-on: ubuntu-latest
    steps:
      - id: delete_tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}