name: Build

on:
  push:
    branches-ignore:
      - releases
      - master
  pull_request:
    branches-ignore:
      - releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2.3.3
      - id: java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - id: maven
        run: mvn package