name: Build

on:
  push:
    branches-ignore:
      - release
      - master
      - breaking-changes
  pull_request:
    branches-ignore:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2.3.3
      - id: java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 8
          distribution: adopt
      - id: maven
        run: mvn package