name: Build

on:
  push:
    branches-ignore: [releases]
  pull_request:
    branches-ignore: [releases]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - run: mvn package --file pom.xml
