name: Build

on:
  push:
    branches-ignore:
      - release
      - master
      - breaking-changes # TODO remove this once merged
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: setup_java
        uses: actions/setup-java@v2.3.4
        with:
          distribution: adopt
          java-version: '8'

      - id: cache_maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - id: build
        run: mvn package --file pom.xml
