name: Release

on:
  push:
    branches:
      - master
      - breaking-changes

jobs:
  release:
    if: github.repository_owner == 'Mooy1'
    runs-on: ubuntu-latest
    steps:

      - id: setup_java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 8
          distribution: adopt

      - id: checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          ref: release

      - id: merge_master
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git merge --no-commit origin/breaking-changes

      - id: get_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: release
          CUSTOM_TAG: 0.0.1
          DRY_RUN: true

      - id: set_version
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.new_tag }}

      - id: maven
        run: mvn package

      - id: changelog
        uses: Bullrich/generate-release-changelog@2.0.1
        env:
          REPO: ${{ github.repository }}

      - id: update_version
        run: |
          git add pom.xml
          git commit -m "set version to ${{ steps.get_version.outputs.new_tag }}"
          git push origin release
          echo ::set-output name=commit::$(git rev-parse HEAD)

      - id: release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.new_tag }}
          release_name: ${{ steps.get_version.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          commitish: ${{ steps.update_version.outputs.commit }}
