name: Release

on:
  push:
    branches:
      - breaking-changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: releases
      - id: get_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: releases
          DRY_RUN: true
          WITH_V: false
      - id: update_version
        run: |
          git merge --no-commit breaking-changes
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.new_tag }}
          git add pom.xml
          git commit -m "Release v${{ steps.get_version.outputs.new_tag }}"
        # git config user.name github-actions
        # git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - id: release
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: releases
          DRY_RUN: true
          WITH_V: true
