name: Release

on:
  push:
    branches:
      - master
      - breaking-changes

jobs:
  release:
    if: github.repository_owner == 'Mooy1'
    runs-on: ubuntu-latest
    steps:
      - id: java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - id: checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          ref: releases
      - id: get_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: releases
          DRY_RUN: true
          WITH_V: false
      - id: update_version
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.new_tag }}
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git merge --no-commit origin/breaking-changes
          git add pom.xml
          git commit -m "Release v${{ steps.get_version.outputs.new_tag }}"
          git push origin releases
      - id: maven
        run: mvn package
      - id: release
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: releases
          DRY_RUN: true
          WITH_V: true
