name: Release

on:
  push:
    branches:
      - master
      - breaking-changes

jobs:
  release:
    if: github.repository_owner == 'Mooy1'
    runs-on: ubuntu-latest
    steps:
      - id: java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 8
          distribution: adopt
      - id: checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          ref: release
      - id: merge_master
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git merge --no-commit origin/breaking-changes
      - id: get_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: release
          CUSTOM_TAG: 0.0.1
          DRY_RUN: true
      - id: update_version
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.new_tag }}
          git add pom.xml
          git commit -m "Release ${{ steps.get_version.outputs.new_tag }}"
          git tag -d 0.0.1
          git push origin release
      - id: maven
        run: mvn package

