name: Release

on:
  push:
    branches:
      - master
      - breaking-changes # todo remove once ready

jobs:
  delete: # todo remove once ready
    if: github.repository_owner != 'Mooy1'
    runs-on: ubuntu-latest
    steps:
    - id: delete_tag
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: 0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.repository_owner == 'Mooy1'
    runs-on: ubuntu-latest
    steps:

      - id: checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          ref: release

      - id: merge_master
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git merge --no-commit origin/breaking-changes

      - id: get_previous_version
        uses: "WyriHaximus/github-action-get-previous-tag@v1.1.0"
        with:
          fallback: 0.0.0

      - id: get_next_version
        uses: "WyriHaximus/github-action-next-semvers@v1.1.0"
        with:
          version: ${{ steps.get_previous_version.outputs.tag }}

      - id: get_version
        run: |
          @echo on
          tag="${{ steps.get_previous_version.outputs.tag }}"
          if [[ $tag == "0.0.0" ]]; then
            echo ::set-output name=version::0.0.1
          else
            commits=$(git log --pretty=format:'%s' "$tag"..HEAD)
            echo "$commits" # todo remove once ready
            case "$commits" in
              *major*)
                echo ::set-output name=version::${{ steps.get_next_version.outputs.major }} ;;
              *minor*)
                echo ::set-output name=version::${{ steps.get_next_version.outputs.minor }} ;;
              *patch*)
                echo ::set-output name=version::${{ steps.get_next_version.outputs.patch }} ;;
              *)
                echo ::set-output name=version::${{ steps.get_next_version.outputs.minor }} ;;
            esac
          fi

      - id: cache_maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - id: set_version
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.version }}

      - id: setup_java
        uses: actions/setup-java@v2.3.0
        with:
          distribution: adopt
          java-version: '8'

      - id: build
        run: mvn package --file pom.xml

      - id: changelog
        if: steps.get_previous_version.outputs.tag != '0.0.0'
        uses: Bullrich/generate-release-changelog@2.0.1
        env:
          REPO: ${{ github.repository }}

      - id: update_version
        run: |
          git add pom.xml
          git commit -m "set version to ${{ steps.get_version.outputs.version }}"
          git push origin release
          echo ::set-output name=commit::$(git rev-parse HEAD)

      - id: release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          commitish: ${{ steps.update_version.outputs.commit }}
