name: Release

on:
  push:
    branches:
      - master
      - breaking-changes # todo remove once ready

jobs:
  delete: # todo remove once ready
    if: github.repository_owner == 'Mooy1'
    runs-on: ubuntu-latest
    steps:
      - id: delete_tag1
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: 0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: delete_tag2
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: 0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: delete_tag3
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: 0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: delete_tag4
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: 0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: delete_tag5
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: 0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: delete_tag6
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: 0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.repository_owner != 'Mooy1'
    runs-on: ubuntu-latest
    steps:

      - id: checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - id: get_previous_version
        uses: "WyriHaximus/github-action-get-previous-tag@v1.1.0"
        with:
          fallback: 0.0.0

      - id: get_next_version
        uses: "WyriHaximus/github-action-next-semvers@v1.1.0"
        with:
          version: ${{ steps.get_previous_version.outputs.tag }}

      - id: cache_maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - id: set_version
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.version }}

      - id: setup_java
        uses: actions/setup-java@v2.3.0
        with:
          distribution: adopt
          java-version: '8'

      - id: build
        run: mvn package --file pom.xml

      - id: changelog
        if: steps.get_previous_version.outputs.tag != '0.0.0'
        uses: Bullrich/generate-release-changelog@2.0.1
        env:
          REPO: ${{ github.repository }}

      - id: release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
