name: Release

on:
  workflow_run:
    workflows: [Java CI]
    #branches: [breaking-changes]
    #types:
    #  - completed
    #  - requested

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.owner }}
          echo ${{ github.event.workflow_run.conclusion }}
  release:
    if: github.owner == `Mooy1` && github.event.workflow_run.conclusion == `success`
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: releases
      - id: get_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: releases
          DRY_RUN: true
          WITH_V: false
      - id: update_version
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git merge --no-commit origin/breaking-changes
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.new_tag }}
          git add pom.xml
          git commit -m "Release v${{ steps.get_version.outputs.new_tag }}"
      - id: release
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: releases
          DRY_RUN: true
          WITH_V: true
