name: Semantic Release

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          semantic_version: 17.4.4
          branch: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
