name: Bump Version

on:
  push:
    branches:
      - breaking-changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: bump_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: breaking-changes
          DRY_RUN: true
          WITH_V: true
      - run: |
          version=$(echo ${{ steps.bump_version.outputs.new_tag }} | cut -dv -f2)
          mvn versions:set -DnewVersion=$version
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add pom.xml
          git commit -m "Bump Version"
          git push origin breaking-changes
